services:
  - type: web
    name: baby-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn baby_backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
