// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrgDB_v4WbyBHwSkVA9WIpPdDFGqt5Bnk',
    appId: '1:1089758434564:web:a55826cf93dbcc2c392c51',
    messagingSenderId: '1089758434564',
    projectId: 'tracking-tots',
    authDomain: 'tracking-tots.firebaseapp.com',
    storageBucket: 'tracking-tots.firebasestorage.app',
    measurementId: 'G-WQ8RY8NBCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTOdLkd7n8VjrV_v65CuFst6ovoc_KYE',
    appId: '1:1089758434564:android:7d11115c52335433392c51',
    messagingSenderId: '1089758434564',
    projectId: 'tracking-tots',
    storageBucket: 'tracking-tots.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhDRdsjMEtqReg-acMv_ziRgXyRvrPOb8',
    appId: '1:1089758434564:ios:904ad7d5eea0e72f392c51',
    messagingSenderId: '1089758434564',
    projectId: 'tracking-tots',
    storageBucket: 'tracking-tots.firebasestorage.app',
    iosBundleId: 'com.example.trackingtots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhDRdsjMEtqReg-acMv_ziRgXyRvrPOb8',
    appId: '1:1089758434564:ios:904ad7d5eea0e72f392c51',
    messagingSenderId: '1089758434564',
    projectId: 'tracking-tots',
    storageBucket: 'tracking-tots.firebasestorage.app',
    iosBundleId: 'com.example.trackingtots',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrgDB_v4WbyBHwSkVA9WIpPdDFGqt5Bnk',
    appId: '1:1089758434564:web:1cc972769fc9560d392c51',
    messagingSenderId: '1089758434564',
    projectId: 'tracking-tots',
    authDomain: 'tracking-tots.firebaseapp.com',
    storageBucket: 'tracking-tots.firebasestorage.app',
    measurementId: 'G-YFYQTYYWNB',
  );

}